# frozen_string_literal: true

source 'https://rubygems.org'
git_source(:github) { |repo| "https://github.com/#{repo}.git" }

ruby '3.0.1'

# Bundle edge Rails instead: gem 'rails', github: 'rails/rails', branch: 'main'
gem 'rails', '~> 6.1', '>= 6.1.3.2'
# Use postgresql as the database for Active Record
gem 'pg', '~> 1.2'
# Use Puma as the app server
gem 'puma', '~> 5.4'
# Build JSON APIs with ease. Read more: https://github.com/rails/jbuilder
# gem 'jbuilder', '~> 2.7'
# Use Redis adapter to run Action Cable in production
# gem 'redis', '~> 4.4'
# Use Active Model has_secure_password
# gem 'bcrypt', '~> 3.1.7'

# Use Active Storage variant
# gem 'image_processing', '~> 1.2'

# Reduces boot times through caching; required in config/boot.rb
gem 'bootsnap', '~> 1.7', require: false

# Use Rack CORS for handling Cross-Origin Resource Sharing (CORS), making cross-origin AJAX possible
gem 'rack-cors', '~> 1.1'

# API
gem 'faraday', '~> 1.0'
gem 'faraday_middleware', '~> 1.0'

# Background Jobs
# gem 'sidekiq', '~> 6.2', '>= 6.2.1'
# gem 'sidekiq_alive', '~> 2.1', '>= 2.0.6'
# gem 'sidekiq-cron', '~> 1.2'
# gem 'sidekiq-failures', '~> 1.0'
# gem 'sidekiq-status', '~> 1.1', '>= 1.1.4'
# gem 'sidekiq-throttled', '~> 0.13'
# gem 'sidekiq-unique-jobs', '~> 7.1', '>= 7.0.9'

# ElasticSearch
# gem 'searchkick', '~> 4.4', '>= 4.4.4'

# Users
# gem 'pundit', '~> 2.1'

# Notifications
# gem 'noticed', '~> 1.4', '>= 1.4.1'

# Track Changes
# gem 'paper_trail', '~> 12.0'

# Soft Delete
# gem 'discard', '~> 1.2'

# Pagination
# gem 'pagy', '~> 3.11'

# Env Variables
gem 'figaro', '~> 1.2'

# Logging
gem 'lograge', '~> 0.11'
# gem 'opentelemetry-api', '~> 1.0.0.rc2'
# gem 'opentelemetry-exporter-otlp', '~> 0.20'
# gem 'opentelemetry-instrumentation-all', '~> 0.19'
# gem 'opentelemetry-sdk', '~> 1.0.0.rc2'
# gem 'sentry-rails', '~> 4.6'
# gem 'sentry-ruby', '~> 4.6'
# gem 'sentry-sidekiq', '~> 4.6'

# Health
# gem 'health_bit', '~> 0.1'

# JSON
# gem 'jsonapi-serializer', '~> 2.2'
gem 'oj', '~> 3.13'

group :development, :test do
  # Call 'byebug' anywhere in the code to stop execution and get a debugger console
  # gem 'bullet', '~> 6.1'
  gem 'byebug', '~> 11.1', platforms: %i[mri mingw x64_mingw]
  gem 'cypress-on-rails', '~> 1.11'
  gem 'database_cleaner-active_record', '~> 2.0'
  gem 'factory_bot_rails', '~> 6.2'
  gem 'faker', '~> 2.18'
  gem 'pry-rails', '~> 0.3'
  gem 'rspec-rails', '~> 5.0'
  # gem 'simplecov', '~> 0.21', require: false
  # gem 'simplecov-lcov', '~> 0.8', require: false
end

group :development do
  gem 'listen', '~> 3.6'
  # Spring speeds up development by keeping your application running in the background. Read more: https://github.com/rails/spring
  gem 'rack-mini-profiler', '~> 2.3'
  gem 'rubocop', '~> 1.19', require: false
  gem 'rubocop-performance', '~> 1.11', require: false
  gem 'rubocop-rails', '~> 2.11', require: false
  gem 'rubocop-rspec', '~> 2.4', require: false
  gem 'rubocop-thread_safety', '~> 0.4', require: false
  gem 'solargraph', '~> 0.43'
  gem 'spring', '~> 2.1'
end

# Windows does not include zoneinfo files, so bundle the tzinfo-data gem
gem 'tzinfo-data', platforms: %i[mingw mswin x64_mingw jruby]
